name: Deploy ASP.NET app to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./ToDoApp.csproj

    - name: Build
      run: dotnet build ./ToDoApp.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./ToDoApp.csproj -c Release -r win-x86 --self-contained true -o ./publish

    - name: Copy web.config
      run: cp ./web.config ./publish/web.config

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'MyTaskManager'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
